"""FastAPI routes for the experimental local BioStack web UI."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse
from fastapi.templating import Jinja2Templates

from biostack.core.config import load_project_config
from biostack.reports.generator import load_metadata_report

TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"
templates = Jinja2Templates(directory=str(TEMPLATE_DIR))
router = APIRouter()


@dataclass(frozen=True)
class ProjectSummary:
    """Small view model for a local BioStack project discovered on disk."""

    name: str
    path: Path
    template: str
    workflow: str
    reports_count: int


@dataclass(frozen=True)
class ReportSummary:
    """Small view model for one JSON/HTML report pair."""

    run_id: str
    project_name: str
    project_path: Path
    json_path: Path
    html_path: Path | None
    status: str
    workflow: str
    started_at: str


def _candidate_roots(base_dir: Path) -> list[Path]:
    roots = [base_dir]
    roots.extend(
        path
        for path in sorted(base_dir.iterdir())
        if path.is_dir() and not path.name.startswith(".")
    )
    return roots


def discover_projects(base_dir: Path | None = None) -> list[ProjectSummary]:
    """Discover BioStack projects below a local base directory."""
    resolved_base = (base_dir or Path.cwd()).resolve()
    projects: list[ProjectSummary] = []
    for candidate in _candidate_roots(resolved_base):
        config_path = candidate / "biostack.yml"
        if not config_path.is_file():
            continue
        try:
            config = load_project_config(config_path)
        except Exception:
            continue
        reports_root = candidate / config.storage.reports
        reports_count = len(list(reports_root.glob("run-*.json"))) if reports_root.is_dir() else 0
        projects.append(
            ProjectSummary(
                name=config.project.name,
                path=candidate,
                template=config.project.template,
                workflow=config.workflow.name,
                reports_count=reports_count,
            )
        )
    return sorted(projects, key=lambda item: (item.name, item.path.as_posix()))


def discover_reports(base_dir: Path | None = None) -> list[ReportSummary]:
    """Discover JSON reports generated by local BioStack projects."""
    reports: list[ReportSummary] = []
    for project in discover_projects(base_dir):
        config = load_project_config(project.path / "biostack.yml")
        reports_root = project.path / config.storage.reports
        for json_path in sorted(reports_root.glob("run-*.json")):
            try:
                metadata = load_metadata_report(json_path)
            except Exception:
                raw: dict[str, Any] = json.loads(json_path.read_text(encoding="utf-8"))
                run_id = str(raw.get("run_id", json_path.stem))
                status = str(raw.get("status", "UNKNOWN"))
                workflow = str(raw.get("workflow", "unknown"))
                started_at = str(raw.get("started_at", ""))
            else:
                run_id = metadata.run_id
                status = metadata.status
                workflow = metadata.workflow
                started_at = metadata.started_at.isoformat()
            html_path = json_path.with_suffix(".html")
            reports.append(
                ReportSummary(
                    run_id=run_id,
                    project_name=project.name,
                    project_path=project.path,
                    json_path=json_path,
                    html_path=html_path if html_path.is_file() else None,
                    status=status,
                    workflow=workflow,
                    started_at=started_at,
                )
            )
    return sorted(reports, key=lambda item: (item.started_at, item.run_id), reverse=True)


@router.get("/")
def index(request: Request):
    """Render a compact local dashboard with projects and recent reports."""
    projects = discover_projects()
    reports = discover_reports()
    return templates.TemplateResponse(
        request,
        "index.html",
        {"projects": projects, "reports": reports[:10]},
    )


@router.get("/projects")
def projects(request: Request):
    """Render discovered local BioStack projects."""
    return templates.TemplateResponse(
        request,
        "index.html",
        {"projects": discover_projects(), "reports": discover_reports()[:10]},
    )


@router.get("/reports")
def reports(request: Request):
    """Render discovered local BioStack reports."""
    return templates.TemplateResponse(
        request,
        "reports.html",
        {"reports": discover_reports()},
    )


@router.get("/reports/{run_id}")
def report_detail(run_id: str):
    """Serve the generated HTML report for a local run id."""
    for report in discover_reports():
        if report.run_id == run_id and report.html_path and report.html_path.is_file():
            return FileResponse(report.html_path, media_type="text/html")
    raise HTTPException(
        status_code=404,
        detail=f"Relatório HTML não encontrado para run '{run_id}'.",
    )
